# yaml-language-server:
# $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json

version: "0.2"
language: en
words:
  - cframe
  - flecs
  - jecs
  - lintable
  - oxlint
  - pnpmfile
  - regen
  - turborepo
  - udim
